sudo: 
  # required
  false

language: 
  c 

services:
  - docker



before_install:
  # # update Docker
  # - sudo apt-get update
  # - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  

  
script:
  - make run
  - docker images
  
  
