sudo: 
  required

language: 
  c 

services:
  - docker

#addons:
#  apt:
#    packages:
#    - gfortran

before_install:
  # update Docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  
  - export AUTHOR=ocramz
  - export PROJ=mpich-docker
  - export DOCKER_NAME=${AUTHOR}/${PROJ}
  
script:
  - docker build -t ${DOCKER_NAME} .
  
  
